# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-08 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190308_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='childcidname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='dealerid',
            field=models.CharField(max_length=100),
        ),
    ]
